package com.zx.omp.mapper;

import com.zx.omp.domain.Tcompany;
import org.apache.ibatis.jdbc.SQL;

public class TcompanySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcompany
     *
     * @mbg.generated
     */
    public String insertSelective(Tcompany record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tcompany");
        
        if (record.getCompid() != null) {
            sql.VALUES("compid", "#{compid,jdbcType=INTEGER}");
        }
        
        if (record.getCompname() != null) {
            sql.VALUES("compname", "#{compname,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcompany
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Tcompany record) {
        SQL sql = new SQL();
        sql.UPDATE("tcompany");
        
        if (record.getCompname() != null) {
            sql.SET("compname = #{compname,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("compid = #{compid,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}