package com.zx.omp.mapper;

import com.zx.omp.domain.Tcompany;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface TcompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcompany
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tcompany",
        "where compid = #{compid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer compid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcompany
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tcompany (compid, compname)",
        "values (#{compid,jdbcType=INTEGER}, #{compname,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys = true, keyProperty = "compid")
    int insert(Tcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcompany
     *
     * @mbg.generated
     */
    @InsertProvider(type=TcompanySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true, keyProperty = "compid")
    int insertSelective(Tcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcompany
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "compid, compname",
        "from tcompany",
        "where compid = #{compid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="compid", property="compid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="compname", property="compname", jdbcType=JdbcType.VARCHAR)
    })
    Tcompany selectByPrimaryKey(Integer compid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcompany
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TcompanySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Tcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcompany
     *
     * @mbg.generated
     */
    @Update({
        "update tcompany",
        "set compname = #{compname,jdbcType=VARCHAR}",
        "where compid = #{compid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Tcompany record);
}