package com.zx.omp.mapper;

import com.zx.omp.domain.Tuser;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface TuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tuser",
        "where iduser = #{iduser,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer iduser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tuser (iduser, compid, ",
        "uname, uemail, upwd, ",
        "create_time, umphone, ",
        "urealname, uisdel, ",
        "utype)",
        "values (#{iduser,jdbcType=INTEGER}, #{compid,jdbcType=INTEGER}, ",
        "#{uname,jdbcType=VARCHAR}, #{uemail,jdbcType=VARCHAR}, #{upwd,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{umphone,jdbcType=VARCHAR}, ",
        "#{urealname,jdbcType=VARCHAR}, #{uisdel,jdbcType=INTEGER}, ",
        "#{utype,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys = true, keyProperty = "iduser")
    int insert(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated
     */
    @InsertProvider(type=TuserSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true, keyProperty = "iduser")
    int insertSelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "iduser, compid, uname, uemail, upwd, create_time, umphone, urealname, uisdel, ",
        "utype",
        "from tuser",
        "where iduser = #{iduser,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="iduser", property="iduser", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="compid", property="compid", jdbcType=JdbcType.INTEGER),
        @Result(column="uname", property="uname", jdbcType=JdbcType.VARCHAR),
        @Result(column="uemail", property="uemail", jdbcType=JdbcType.VARCHAR),
        @Result(column="upwd", property="upwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="umphone", property="umphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="urealname", property="urealname", jdbcType=JdbcType.VARCHAR),
        @Result(column="uisdel", property="uisdel", jdbcType=JdbcType.INTEGER),
        @Result(column="utype", property="utype", jdbcType=JdbcType.INTEGER)
    })
    Tuser selectByPrimaryKey(Integer iduser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TuserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated
     */
    @Update({
        "update tuser",
        "set compid = #{compid,jdbcType=INTEGER},",
          "uname = #{uname,jdbcType=VARCHAR},",
          "uemail = #{uemail,jdbcType=VARCHAR},",
          "upwd = #{upwd,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "umphone = #{umphone,jdbcType=VARCHAR},",
          "urealname = #{urealname,jdbcType=VARCHAR},",
          "uisdel = #{uisdel,jdbcType=INTEGER},",
          "utype = #{utype,jdbcType=INTEGER}",
        "where iduser = #{iduser,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Tuser record);
}