package com.zx.omp.mapper;

import com.zx.omp.domain.Tuser;
import org.apache.ibatis.jdbc.SQL;

public class TuserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated
     */
    public String insertSelective(Tuser record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tuser");
        
        if (record.getIduser() != null) {
            sql.VALUES("iduser", "#{iduser,jdbcType=INTEGER}");
        }
        
        if (record.getCompid() != null) {
            sql.VALUES("compid", "#{compid,jdbcType=INTEGER}");
        }
        
        if (record.getUname() != null) {
            sql.VALUES("uname", "#{uname,jdbcType=VARCHAR}");
        }
        
        if (record.getUemail() != null) {
            sql.VALUES("uemail", "#{uemail,jdbcType=VARCHAR}");
        }
        
        if (record.getUpwd() != null) {
            sql.VALUES("upwd", "#{upwd,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUmphone() != null) {
            sql.VALUES("umphone", "#{umphone,jdbcType=VARCHAR}");
        }
        
        if (record.getUrealname() != null) {
            sql.VALUES("urealname", "#{urealname,jdbcType=VARCHAR}");
        }
        
        if (record.getUisdel() != null) {
            sql.VALUES("uisdel", "#{uisdel,jdbcType=INTEGER}");
        }
        
        if (record.getUtype() != null) {
            sql.VALUES("utype", "#{utype,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuser
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Tuser record) {
        SQL sql = new SQL();
        sql.UPDATE("tuser");
        
        if (record.getCompid() != null) {
            sql.SET("compid = #{compid,jdbcType=INTEGER}");
        }
        
        if (record.getUname() != null) {
            sql.SET("uname = #{uname,jdbcType=VARCHAR}");
        }
        
        if (record.getUemail() != null) {
            sql.SET("uemail = #{uemail,jdbcType=VARCHAR}");
        }
        
        if (record.getUpwd() != null) {
            sql.SET("upwd = #{upwd,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUmphone() != null) {
            sql.SET("umphone = #{umphone,jdbcType=VARCHAR}");
        }
        
        if (record.getUrealname() != null) {
            sql.SET("urealname = #{urealname,jdbcType=VARCHAR}");
        }
        
        if (record.getUisdel() != null) {
            sql.SET("uisdel = #{uisdel,jdbcType=INTEGER}");
        }
        
        if (record.getUtype() != null) {
            sql.SET("utype = #{utype,jdbcType=INTEGER}");
        }
        
        sql.WHERE("iduser = #{iduser,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}