package com.zx.omp.domain;

public class Tcompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcompany.compid
     *
     * @mbg.generated
     */
    private Integer compid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcompany.compname
     *
     * @mbg.generated
     */
    private String compname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcompany.compid
     *
     * @return the value of tcompany.compid
     *
     * @mbg.generated
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcompany.compid
     *
     * @param compid the value for tcompany.compid
     *
     * @mbg.generated
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcompany.compname
     *
     * @return the value of tcompany.compname
     *
     * @mbg.generated
     */
    public String getCompname() {
        return compname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcompany.compname
     *
     * @param compname the value for tcompany.compname
     *
     * @mbg.generated
     */
    public void setCompname(String compname) {
        this.compname = compname == null ? null : compname.trim();
    }
}