package com.zx.omp.domain;

import java.util.Date;

public class Tuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.iduser
     *
     * @mbg.generated
     */
    private Integer iduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.compid
     *
     * @mbg.generated
     */
    private Integer compid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.uname
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.uemail
     *
     * @mbg.generated
     */
    private String uemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.upwd
     *
     * @mbg.generated
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.umphone
     *
     * @mbg.generated
     */
    private String umphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.urealname
     *
     * @mbg.generated
     */
    private String urealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.uisdel
     *
     * @mbg.generated
     */
    private Integer uisdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuser.utype
     *
     * @mbg.generated
     */
    private Integer utype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.iduser
     *
     * @return the value of tuser.iduser
     *
     * @mbg.generated
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.iduser
     *
     * @param iduser the value for tuser.iduser
     *
     * @mbg.generated
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.compid
     *
     * @return the value of tuser.compid
     *
     * @mbg.generated
     */
    public Integer getCompid() {
        return compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.compid
     *
     * @param compid the value for tuser.compid
     *
     * @mbg.generated
     */
    public void setCompid(Integer compid) {
        this.compid = compid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.uname
     *
     * @return the value of tuser.uname
     *
     * @mbg.generated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.uname
     *
     * @param uname the value for tuser.uname
     *
     * @mbg.generated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.uemail
     *
     * @return the value of tuser.uemail
     *
     * @mbg.generated
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.uemail
     *
     * @param uemail the value for tuser.uemail
     *
     * @mbg.generated
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.upwd
     *
     * @return the value of tuser.upwd
     *
     * @mbg.generated
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.upwd
     *
     * @param upwd the value for tuser.upwd
     *
     * @mbg.generated
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.create_time
     *
     * @return the value of tuser.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.create_time
     *
     * @param createTime the value for tuser.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.umphone
     *
     * @return the value of tuser.umphone
     *
     * @mbg.generated
     */
    public String getUmphone() {
        return umphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.umphone
     *
     * @param umphone the value for tuser.umphone
     *
     * @mbg.generated
     */
    public void setUmphone(String umphone) {
        this.umphone = umphone == null ? null : umphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.urealname
     *
     * @return the value of tuser.urealname
     *
     * @mbg.generated
     */
    public String getUrealname() {
        return urealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.urealname
     *
     * @param urealname the value for tuser.urealname
     *
     * @mbg.generated
     */
    public void setUrealname(String urealname) {
        this.urealname = urealname == null ? null : urealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.uisdel
     *
     * @return the value of tuser.uisdel
     *
     * @mbg.generated
     */
    public Integer getUisdel() {
        return uisdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.uisdel
     *
     * @param uisdel the value for tuser.uisdel
     *
     * @mbg.generated
     */
    public void setUisdel(Integer uisdel) {
        this.uisdel = uisdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tuser.utype
     *
     * @return the value of tuser.utype
     *
     * @mbg.generated
     */
    public Integer getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tuser.utype
     *
     * @param utype the value for tuser.utype
     *
     * @mbg.generated
     */
    public void setUtype(Integer utype) {
        this.utype = utype;
    }
}